### ISSUE TITLE
[Issue] Issue with jetbrains icosn

### ISSUE THREAD

**Issue by ruadoVn** [EliverLara/candy-icons#344] opened 2021-12-06 03:20 UTC
I'm using Arch And I am using KDE Plasma with candy-icons. 
But why is my JetBrains Tools don't have candy icons?

**Comment by EliverLara** [comment] 2021-12-27 21:35
Please check if those applications aren't installed through snap.

**Comment by ratijas** [comment] 2022-02-04 19:24
Hi, @ruadoVn, you are likely hitting [this issue](https://bugs.kde.org/show_bug.cgi?id=351055) which has some workarounds to it, but unfortunately is conceptually unfixable in XOrg/X11.

Additionally, JetBrains installer hardcodes paths to icons in their .desktop files, so you may need to manually edit each of them to specify a generic path-less icon. For example:

- Go to _~/.local/share/applications_
- Open _jetbrains-clion.desktop_ in text editor
- Replace the _Icon=~/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/.icon.svg_ with simply _Icon=jetbrains-clion.svg_ (that's how the icon is named in _~/.local/share/icons/candy-icons/apps/scalable/_

@EliverLara this issue should be closed as out of close for candy-icons. Unfortunately, there's not much we can do here.

**Comment by ratijas** [comment] 2022-02-04 19:28
Duplicate of: https://github.com/EliverLara/candy-icons/issues/293

**Closed** 2022-02-12 19:41 UTC
Labels: duplicate
